#!/bin/bash -x
cmake .. -D CMAKE_BUILD_TYPE=Debug -DBUILD_CLIENT=ON -DBUILD_SERVER=ON -DBUILD_WITH_PULSE=ON \
  -DBUILD_WITH_JACK=ON -DBUILD_WITH_PIPEWIRE=ON\
  -DBUILD_WITH_LIBRIST=ON -DCMAKE_INSTALL_FULL_SYSCONFDIR=/etc;
